
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mloub
 */
public class FenetreQuiz extends javax.swing.JFrame {
    private ArrayList<Question> listeQuestions;
    private int indexQuestionCourante = 0;
    private int score = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
    
   
    public FenetreQuiz() {
        initComponents();
        initialiserQuestions();
        afficherQuestionCourante();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        QuestionSuivante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setText("Question");

        btnRep1.setText("btnRep1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setText("btnRep2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setText("btnRep3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setText("btnRep4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        lblFeedback.setText("Bonne Réponse");

        lblScore.setText("Score:");

        QuestionSuivante.setText("Question suivante");
        QuestionSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionSuivanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRep1)
                            .addComponent(btnRep2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblQuestion)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRep4)
                            .addComponent(btnRep3))
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFeedback)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 252, Short.MAX_VALUE)
                        .addComponent(QuestionSuivante)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblScore)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep1)
                    .addComponent(btnRep3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep4)
                    .addComponent(btnRep2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(lblFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuestionSuivante)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        // TODO add your handling code here:
        verifierReponse(1);
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        // TODO add your handling code here:
        verifierReponse(3);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        // TODO add your handling code here:
        verifierReponse(4);
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        // TODO add your handling code here:
        verifierReponse(2);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void QuestionSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionSuivanteActionPerformed
        indexQuestionCourante++;
        if (indexQuestionCourante < listeQuestions.size()) {
            afficherQuestionCourante();
        } else {
            lblQuestion.setText("FIN DU QUIZ !");
            lblFeedback.setText("Quiz terminé. Score final : " + score + " / " + listeQuestions.size());
            QuestionSuivante.setEnabled(false);
            lblScore.setText("Score final : " + score + " / " + listeQuestions.size());
        }
    }//GEN-LAST:event_QuestionSuivanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuestionSuivante;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

    private void initialiserQuestions() {
        listeQuestions = new ArrayList<>();
        
        listeQuestions.add(new Question(
            "Quel est le plus grand océan du monde ?",
            "Océan Atlantique", "Océan Pacifique", "Océan Indien", "Océan Arctique", 2));
        listeQuestions.add(new Question(
            "Quelle est la formule chimique de l’eau ?",
            "CO₂", "H₂O", "O₂", "NaCl", 2));
        listeQuestions.add(new Question(
            "En quelle année a eu lieu la prise de la Bastille ?",
            "1789", "1815", "1776", "1792", 1));
        listeQuestions.add(new Question(
            "Quel est le pays le plus peuplé au monde ?",
            "Inde", "États-Unis", "Chine", "Indonésie", 3));
        listeQuestions.add(new Question(
            "Quelle marque de voitures est-elle allemande ?",
            "Peugeot", "Cadillac", "Volvo", "Mini", 4));

    }

    private void afficherQuestionCourante() {
    if (indexQuestionCourante < listeQuestions.size()) {
        Question question = listeQuestions.get(indexQuestionCourante); // <-- On affiche SEULEMENT si l'index est valide

        lblQuestion.setText(question.getIntitule());
        
        btnRep1.setText(question.getProposition1());
        btnRep2.setText(question.getProposition2());
        btnRep3.setText(question.getProposition3());
        btnRep4.setText(question.getProposition4());

        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);

        QuestionSuivante.setEnabled(false);
        
        lblFeedback.setText("Choisissez une réponse...");
        // Mettre à jour le score initial
        lblScore.setText("Score : " + score + " / " + listeQuestions.size());
    } else {
        // Logique de fin de quiz, au cas où cette méthode est appelée lorsque le quiz est déjà terminé
        lblQuestion.setText("FIN DU QUIZ !");
        lblFeedback.setText("Quiz terminé. Score final : " + score + " / " + listeQuestions.size());
        QuestionSuivante.setEnabled(false);
        lblScore.setText("Score final : " + score + " / " + listeQuestions.size());

    }
    }

    private void verifierReponse(int reponseChoisie) {
        Question questionCourante = listeQuestions.get(indexQuestionCourante);

         if (reponseChoisie == questionCourante.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !!");
            score++;
        } else {
            lblFeedback.setText("Mauvaise réponse. La bonne réponse était la proposition " + questionCourante.getIndexBonneReponse() + ".");
            
        }

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
        
        QuestionSuivante.setEnabled(true);
        
        lblScore.setText("Score:" + score + "/" + (indexQuestionCourante + 1));
    }   
}
