/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadenas;

/**
 *
 * @author mloub
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_Intro = new javax.swing.JLabel();
        Tester = new javax.swing.JButton();
        txt_lbl_nb_chiffre_exact = new javax.swing.JLabel();
        txt_nb_chiffre_exact = new javax.swing.JLabel();
        txt_lbl_nb_chiffre_trop_haut = new javax.swing.JLabel();
        txt_nb_chiffre_trop_haut = new javax.swing.JLabel();
        txt_lbl_nb_chiffre_trop_bas = new javax.swing.JLabel();
        txt_nb_chiffre_trop_bas = new javax.swing.JLabel();
        txt_score = new javax.swing.JLabel();
        txt_tentatives = new javax.swing.JLabel();
        recommencer = new javax.swing.JButton();
        up_chiffre4 = new javax.swing.JButton();
        chiffre1 = new javax.swing.JLabel();
        up_chiffre1 = new javax.swing.JButton();
        down_chiffre2 = new javax.swing.JButton();
        up_chiffre2 = new javax.swing.JButton();
        chiffre4 = new javax.swing.JLabel();
        down_chiffre4 = new javax.swing.JButton();
        down_chiffre1 = new javax.swing.JButton();
        chiffre2 = new javax.swing.JLabel();
        up_chiffre3 = new javax.swing.JButton();
        chiffre3 = new javax.swing.JLabel();
        down_chiffre3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_Intro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_Intro.setText("Trouver le bon code en moins de 5 tentatives");
        getContentPane().add(texte_Intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 14, 307, -1));

        Tester.setText("Tester");
        getContentPane().add(Tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 120, -1, -1));

        txt_lbl_nb_chiffre_exact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_lbl_nb_chiffre_exact.setText("Nombre de chiffres exacts :");
        getContentPane().add(txt_lbl_nb_chiffre_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, 154, -1));

        txt_nb_chiffre_exact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nb_chiffre_exact.setText("0");
        getContentPane().add(txt_nb_chiffre_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 186, 33, -1));

        txt_lbl_nb_chiffre_trop_haut.setText("Nombre de chiffres trop hauts :");
        getContentPane().add(txt_lbl_nb_chiffre_trop_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, 184, -1));

        txt_nb_chiffre_trop_haut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nb_chiffre_trop_haut.setText("0");
        getContentPane().add(txt_nb_chiffre_trop_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 222, 59, -1));

        txt_lbl_nb_chiffre_trop_bas.setText("Nombre de chiffres trop bas :");
        getContentPane().add(txt_lbl_nb_chiffre_trop_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 256, 173, -1));

        txt_nb_chiffre_trop_bas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nb_chiffre_trop_bas.setText("0");
        getContentPane().add(txt_nb_chiffre_trop_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 256, 37, -1));

        txt_score.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        txt_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_score.setText("0/5");
        getContentPane().add(txt_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 244, 72, 30));

        txt_tentatives.setText("Tentatives");
        getContentPane().add(txt_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 194, 92, -1));

        recommencer.setBackground(new java.awt.Color(0, 102, 102));
        recommencer.setForeground(new java.awt.Color(255, 255, 255));
        recommencer.setText("Recommencer");
        recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 280, -1, -1));

        up_chiffre4.setText("/\\");
            getContentPane().add(up_chiffre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 53, 46));

            chiffre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            chiffre1.setText("0");
            getContentPane().add(chiffre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 53, 46));

            up_chiffre1.setText("/\\");
                getContentPane().add(up_chiffre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 53, 46));

                down_chiffre2.setText("\\/");
                down_chiffre2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        down_chiffre2ActionPerformed(evt);
                    }
                });
                getContentPane().add(down_chiffre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 73, 46));

                up_chiffre2.setText("/\\");
                    getContentPane().add(up_chiffre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 73, 46));

                    chiffre4.setBackground(new java.awt.Color(255, 255, 255));
                    chiffre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    chiffre4.setText("0");
                    chiffre4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
                    getContentPane().add(chiffre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 73, 46));

                    down_chiffre4.setBackground(new java.awt.Color(0, 102, 102));
                    down_chiffre4.setText("\\/");
                    getContentPane().add(down_chiffre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 70, 40));

                    down_chiffre1.setText("\\/");
                    getContentPane().add(down_chiffre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 112, 46));

                    chiffre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    chiffre2.setText("0");
                    getContentPane().add(chiffre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 112, 46));

                    up_chiffre3.setText("/\\");
                        getContentPane().add(up_chiffre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 40, 30));

                        chiffre3.setBackground(new java.awt.Color(255, 204, 204));
                        chiffre3.setForeground(new java.awt.Color(255, 204, 204));
                        chiffre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        chiffre3.setText("0");
                        chiffre3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
                        getContentPane().add(chiffre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 60, 30));

                        down_chiffre3.setText("\\/");
                        getContentPane().add(down_chiffre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 80, 40));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void down_chiffre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre2ActionPerformed

    private void recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommencerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tester;
    private javax.swing.JLabel chiffre1;
    private javax.swing.JLabel chiffre2;
    private javax.swing.JLabel chiffre3;
    private javax.swing.JLabel chiffre4;
    private javax.swing.JButton down_chiffre1;
    private javax.swing.JButton down_chiffre2;
    private javax.swing.JButton down_chiffre3;
    private javax.swing.JButton down_chiffre4;
    private javax.swing.JButton recommencer;
    private javax.swing.JLabel texte_Intro;
    private javax.swing.JLabel txt_lbl_nb_chiffre_exact;
    private javax.swing.JLabel txt_lbl_nb_chiffre_trop_bas;
    private javax.swing.JLabel txt_lbl_nb_chiffre_trop_haut;
    private javax.swing.JLabel txt_nb_chiffre_exact;
    private javax.swing.JLabel txt_nb_chiffre_trop_bas;
    private javax.swing.JLabel txt_nb_chiffre_trop_haut;
    private javax.swing.JLabel txt_score;
    private javax.swing.JLabel txt_tentatives;
    private javax.swing.JButton up_chiffre1;
    private javax.swing.JButton up_chiffre2;
    private javax.swing.JButton up_chiffre3;
    private javax.swing.JButton up_chiffre4;
    // End of variables declaration//GEN-END:variables
}
