/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadenas;

/**
 *
 * @author mloub
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_Intro = new javax.swing.JLabel();
        down_chiffre1 = new javax.swing.JButton();
        down_chiffre2 = new javax.swing.JButton();
        down_chiffre3 = new javax.swing.JButton();
        down_chiffre4 = new javax.swing.JButton();
        up_chiffre1 = new javax.swing.JButton();
        up_chiffre2 = new javax.swing.JButton();
        up_chiffre3 = new javax.swing.JButton();
        up_chiffre4 = new javax.swing.JButton();
        chiffre1 = new javax.swing.JLabel();
        chiffre2 = new javax.swing.JLabel();
        chiffre3 = new javax.swing.JLabel();
        chiffre4 = new javax.swing.JLabel();
        Tester = new javax.swing.JButton();
        txt_lbl_nb_chiffre_exact = new javax.swing.JLabel();
        txt_nb_chiffre_exact = new javax.swing.JLabel();
        txt_lbl_nb_chiffre_trop_haut = new javax.swing.JLabel();
        txt_nb_chiffre_trop_haut = new javax.swing.JLabel();
        txt_lbl_nb_chiffre_trop_bas = new javax.swing.JLabel();
        txt_nb_chiffre_trop_bas = new javax.swing.JLabel();
        txt_score = new javax.swing.JLabel();
        txt_tentatives = new javax.swing.JLabel();
        recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        texte_Intro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_Intro.setText("Trouver le bon code en moins de 5 tentatives");

        down_chiffre1.setText("\\/");

        down_chiffre2.setText("\\/");
        down_chiffre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre2ActionPerformed(evt);
            }
        });

        down_chiffre3.setText("\\/");

        down_chiffre4.setText("\\/");

        up_chiffre1.setText("/\\");

            up_chiffre2.setText("/\\");

                up_chiffre3.setText("/\\");

                    up_chiffre4.setText("/\\");

                        chiffre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        chiffre1.setText("0");

                        chiffre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        chiffre2.setText("0");

                        chiffre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        chiffre3.setText("0");

                        chiffre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        chiffre4.setText("0");

                        Tester.setText("Tester");

                        txt_lbl_nb_chiffre_exact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                        txt_lbl_nb_chiffre_exact.setText("Nombre de chiffres exacts :");

                        txt_nb_chiffre_exact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        txt_nb_chiffre_exact.setText("0");

                        txt_lbl_nb_chiffre_trop_haut.setText("Nombre de chiffres trop hauts :");

                        txt_nb_chiffre_trop_haut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        txt_nb_chiffre_trop_haut.setText("0");

                        txt_lbl_nb_chiffre_trop_bas.setText("Nombre de chiffres trop bas :");

                        txt_nb_chiffre_trop_bas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        txt_nb_chiffre_trop_bas.setText("0");

                        txt_score.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
                        txt_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        txt_score.setText("0/5");

                        txt_tentatives.setText("Tentatives");

                        recommencer.setBackground(new java.awt.Color(0, 102, 102));
                        recommencer.setForeground(new java.awt.Color(255, 255, 255));
                        recommencer.setText("Recommencer");
                        recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                recommencerActionPerformed(evt);
                            }
                        });

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(down_chiffre1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(down_chiffre2)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(down_chiffre3))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(up_chiffre1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(up_chiffre2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(up_chiffre3)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(down_chiffre4)
                                                        .addGap(47, 47, 47)
                                                        .addComponent(Tester))
                                                    .addComponent(up_chiffre4)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(87, 87, 87)
                                                .addComponent(texte_Intro, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(139, 139, 139)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(txt_lbl_nb_chiffre_trop_bas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(txt_nb_chiffre_trop_bas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(txt_lbl_nb_chiffre_exact, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(48, 48, 48)
                                                            .addComponent(txt_nb_chiffre_exact, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(txt_lbl_nb_chiffre_trop_haut, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(txt_nb_chiffre_trop_haut, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_score, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(recommencer)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(chiffre1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(chiffre2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(chiffre3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(chiffre4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(52, Short.MAX_VALUE))
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(texte_Intro)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(up_chiffre1)
                                    .addComponent(up_chiffre2)
                                    .addComponent(up_chiffre3)
                                    .addComponent(up_chiffre4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(chiffre3)
                                            .addComponent(chiffre4)
                                            .addComponent(chiffre2)
                                            .addComponent(chiffre1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Tester))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(down_chiffre4)
                                                    .addComponent(down_chiffre3)
                                                    .addComponent(down_chiffre2)
                                                    .addComponent(down_chiffre1))))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_lbl_nb_chiffre_exact)
                                            .addComponent(txt_nb_chiffre_exact)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(txt_tentatives)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_lbl_nb_chiffre_trop_haut)
                                            .addComponent(txt_nb_chiffre_trop_haut))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_lbl_nb_chiffre_trop_bas)
                                            .addComponent(txt_nb_chiffre_trop_bas)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(txt_score, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recommencer)
                                .addContainerGap())
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void down_chiffre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre2ActionPerformed

    private void recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommencerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tester;
    private javax.swing.JLabel chiffre1;
    private javax.swing.JLabel chiffre2;
    private javax.swing.JLabel chiffre3;
    private javax.swing.JLabel chiffre4;
    private javax.swing.JButton down_chiffre1;
    private javax.swing.JButton down_chiffre2;
    private javax.swing.JButton down_chiffre3;
    private javax.swing.JButton down_chiffre4;
    private javax.swing.JButton recommencer;
    private javax.swing.JLabel texte_Intro;
    private javax.swing.JLabel txt_lbl_nb_chiffre_exact;
    private javax.swing.JLabel txt_lbl_nb_chiffre_trop_bas;
    private javax.swing.JLabel txt_lbl_nb_chiffre_trop_haut;
    private javax.swing.JLabel txt_nb_chiffre_exact;
    private javax.swing.JLabel txt_nb_chiffre_trop_bas;
    private javax.swing.JLabel txt_nb_chiffre_trop_haut;
    private javax.swing.JLabel txt_score;
    private javax.swing.JLabel txt_tentatives;
    private javax.swing.JButton up_chiffre1;
    private javax.swing.JButton up_chiffre2;
    private javax.swing.JButton up_chiffre3;
    private javax.swing.JButton up_chiffre4;
    // End of variables declaration//GEN-END:variables
}
